---
# tasks file for siteDev | Setup

# Setup | configure current MySQL instance
# ----------------------------------------

- name: Setup | MySQL Users
  mysql_user: name=gome password=gome@secret priv=*.*:ALL state=present

- name: Setup | MySQL Databases
  mysql_db: name=gome state=present

# Setup | build and make the application available
# ------------------------------------------------

- name: Setup | Composer Global Require
  command: >
      composer global require "{{ item.package }}:{{ item.version }}"
      creates=/home/vagrant/.config/composer/vendor/{{ item.package }}/composer.json
  with_items:
    - { package: fxp/composer-asset-plugin, version: ~1.1.3 }
  become_user: vagrant

- name: Setup | Composer Install
  composer: command=install working_dir=/vagrant
  become_user: vagrant
  notify:
      - yii2 | migrate

# Setup | apache2 under vagrant user/group
# ----------------------------------------

- name: "Setup | Apache2 Under Vagrant User"
  lineinfile:
    dest: "/etc/apache2/envvars"
    regexp: "^export APACHE_RUN_USER="
    line: "export APACHE_RUN_USER=vagrant"
    state: present
  notify:
    - apache2 | restart

- name: "Setup | Apache2 Under Vagrant Group"
  lineinfile:
    dest: "/etc/apache2/envvars"
    regexp: "^export APACHE_RUN_GROUP="
    line: "export APACHE_RUN_GROUP=vagrant"
    state: present
  notify:
    - apache2 | restart