#!/usr/bin/env php

<?php

defined( 'YII_DEBUG' ) or define( 'YII_DEBUG', TRUE );
defined( 'STDIN' ) or define( 'STDIN', fopen( 'php://stdin', 'r' ) );
defined( 'STDOUT' ) or define( 'STDOUT', fopen( 'php://stdout', 'w' ) );

require( __DIR__ . '/../vendor/autoload.php' );
require( __DIR__ . '/../vendor/yiisoft/yii2/Yii.php' );
require( __DIR__ . '/../shared/config/bootstrap.php' );

$config = yii\helpers\ArrayHelper::merge(
    require( __DIR__ . '/../shared/config/main.php' ),
    require( __DIR__ . '/config/main.php' )
);

exit( ( new yii\console\Application( $config ) )->run() );